import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@clerk/nextjs/server'
import { createAdminClient } from '@/lib/supabase/server'
import { createAnthropicClient, AI_MODEL, MAX_TOKENS } from '@/lib/anthropic/client'

const TOKEN_COST = 5

const FORMAT_LABELS: Record<string, string> = {
  reel:     'Reel (video corto 15-30s)',
  historia: 'Historia / Story (15s)',
  carrusel: 'Carrusel (5-8 slides)',
  post:     'Post estático (imagen + caption)',
}

const OBJECTIVE_LABELS: Record<string, string> = {
  proceso:      'Mostrar proceso de tatuaje',
  antesdespues: 'Antes y después',
  flash:        'Flash tattoo / disponibilidad',
  estilo:       'Mostrar estilo específico',
  testimonio:   'Testimonio de cliente',
  educativo:    'Contenido educativo / consejos',
}

/**
 * POST /api/ai/contenido
 *
 * Body: { format: string, objective: string }
 *
 * Streams a JSON content idea generated by Claude, then deducts 5 tokens.
 *
 * Generated JSON shape:
 * {
 *   title:    string           — descriptive idea title
 *   hook:     string           — opening hook text (first 3 seconds)
 *   script:   { time, action }[] — shot-by-shot breakdown
 *   caption:  string           — Instagram caption (≤ 150 words)
 *   hashtags: string           — space-separated hashtags (8-12 tags)
 * }
 */
export async function POST(req: NextRequest) {
  // ── Auth ──────────────────────────────────────────────────────────────────
  const { userId } = await auth()
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // ── Parse body ────────────────────────────────────────────────────────────
  let body: { format?: string; objective?: string }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const format    = body.format    ?? 'reel'
  const objective = body.objective ?? 'proceso'

  // ── Fetch business ────────────────────────────────────────────────────────
  const supabase = createAdminClient()

  const { data: biz, error: bizErr } = await supabase
    .from('businesses')
    .select('id, name, city, country, styles, tv_tokens_balance')
    .eq('user_id', userId)
    .single()

  if (bizErr || !biz) {
    return NextResponse.json({ error: 'Business not found — complete onboarding first' }, { status: 404 })
  }

  const balance = biz.tv_tokens_balance ?? 0
  if (balance < TOKEN_COST) {
    return NextResponse.json(
      { error: `Insufficient TV tokens — need ${TOKEN_COST}, have ${balance}` },
      { status: 402 }
    )
  }

  // ── Deduct tokens before streaming ────────────────────────────────────────
  await supabase
    .from('businesses')
    .update({ tv_tokens_balance: balance - TOKEN_COST })
    .eq('id', biz.id)

  // ── Build prompt ──────────────────────────────────────────────────────────
  const stylesStr   = (biz.styles as string[] | null ?? []).join(', ') || 'tatuajes en general'
  const locationStr = [biz.city, biz.country].filter(Boolean).join(', ') || 'Latinoamérica'
  const fmtLabel    = FORMAT_LABELS[format]    ?? format
  const objLabel    = OBJECTIVE_LABELS[objective] ?? objective

  const prompt = `Eres un experto en contenido para Instagram de estudios de tatuajes en Latinoamérica.

Datos del estudio:
- Nombre: ${biz.name}
- Ubicación: ${locationStr}
- Estilos especializados: ${stylesStr}
- Formato solicitado: ${fmtLabel}
- Objetivo del contenido: ${objLabel}

Genera UNA idea de contenido detallada, creativa y lista para producir, en JSON con exactamente estos campos:
{
  "title": "título descriptivo de la idea (ej: 'Reel: Proceso completo de realismo')",
  "hook": "texto del hook de apertura (primeros 3 segundos, curioso y provocador, máx 120 chars)",
  "script": [
    {"time": "0-3s",   "action": "descripción de lo que se muestra/dice"},
    {"time": "3-8s",   "action": "descripción"},
    {"time": "8-20s",  "action": "descripción"},
    {"time": "20-25s", "action": "descripción"},
    {"time": "25-30s", "action": "CTA final"}
  ],
  "caption": "caption para Instagram (2 párrafos cortos + llamada a la acción, máx 150 palabras, en español)",
  "hashtags": "#hashtag1 #hashtag2 ... (exactamente 10 hashtags relevantes para tatuajes en Latinoamérica)"
}

Adapta el guión según el formato: para Historias (15s) usa 3-4 escenas cortas; para Carrusel describe cada slide; para Posts describe la imagen ideal.

Responde ÚNICAMENTE con el JSON válido. Sin texto adicional, sin markdown, sin bloques de código.`

  // ── Stream from Anthropic ─────────────────────────────────────────────────
  const anthropic = createAnthropicClient()

  const aiStream = anthropic.messages.stream({
    model:      AI_MODEL,
    max_tokens: MAX_TOKENS,
    messages:   [{ role: 'user', content: prompt }],
  })

  const readable = new ReadableStream({
    async start(controller) {
      const encoder = new TextEncoder()
      try {
        for await (const event of aiStream) {
          if (event.type === 'content_block_delta') {
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const text: string | undefined = (event.delta as any).text
            if (text) controller.enqueue(encoder.encode(text))
          }
        }
      } catch (err) {
        console.error('[POST /api/ai/contenido] Stream error:', err)
      } finally {
        controller.close()
      }
    },
    cancel() {
      aiStream.abort()
    },
  })

  return new Response(readable, {
    headers: {
      'Content-Type':      'text/plain; charset=utf-8',
      'Transfer-Encoding': 'chunked',
      'X-Tokens-Deducted': String(TOKEN_COST),
    },
  })
}
